### ISSUE TITLE
D&D 4e Powers Unsupported

### ISSUE THREAD

**Issue by TheCabinetKing** [etiquettestartshere/scenemessage#35]
Currently, D&D 4e abilities are pinged in a way that bypasses all filters, including OOC and whispers (though they should probably be classified under rolls anyway). This goblin's basic attack is visible from scene A:
![image](https://github.com/user-attachments/assets/5b1decf9-836b-4630-8dfa-a61f25dc94f8)

Even though its attack was actually rolled in scene B (forgive me for not rolling to-hit):
![image](https://github.com/user-attachments/assets/622eb374-d758-44e5-8e5f-343a51bef1fe)

**Comment by etiquettestartshere** [comment]
could you hit ctrl+shift+c and element select the chatcard, find the top level element of the chatcard, and show me a screenshot of the elements tab of the dev tools? i might be able to add support via just that. if not, i can download the system at some future time and mess around with it

**Comment by TheCabinetKing** [comment]
Apologies for the wait, webdev is completely alien to me so I hemmed and hawed for a while about what you meant by "elements tab". I'm assuming this is what you're after?
![image](https://github.com/user-attachments/assets/f3783962-8c43-4514-8c5b-2fe912f6aa0e)
I'm happy to use any requested means to verify whether the `dnd4e` tag is an easy solution (instead of worrying about every `item-card`, `power-card`, and edge case that results from the card-specific tags), if it is helpful!

**Comment by etiquettestartshere** [comment]
I think that should be enough, thanks. if its not, ill have to dive in anyway :pray:. I do think simply filtering all `dnd4e` messages will be enough, as long as I also account for whispers etc, since, presumably, some cards with that class can also be whispers. may end up taking a look at the system myself anyway. ill sleep on it 👍  thanks for your help and the report

**Comment by etiquettestartshere** [comment]
sorry this one took a bit. I had to think on it for a while and I decided, in the end, adding an ever-growing list of system specific sorts was not what I wanted to do unless I had no choice, and decided on a more blanket approach that should, I hope, drastically increase compatibility with many systems that have decided not to mark certain system-generated chat messages with `scene`. Let me know if it causes problems 🙏

**Comment by TheCabinetKing** [comment]
Apologies for the wait in kind, multiple factors have been keeping me too busy to engage in much hobby-wise until today, and my notifications have been acting up, besides.

I just tested it, and everything is being correctly filtered! Thank you very much for your hard work! I'll make a new issue if anything somehow comes up (though the solution seems fully comprehensive); in the meantime, you have my eternal gratitude, haha.
